import {cleanUrl} from '../../src/inspiration/model.js';
async function getJson(url,token,fetcher){const response=await fetcher(url,{headers:{authorization:`Bearer ${token}`,'Avif-Fallback':'1'},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`Provider returned HTTP ${response.status}. Check the server token or retry later.`);const reader=response.body?.getReader();if(!reader)return response.json();let size=0;const chunks=[];try{while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>2_000_000)throw new Error('Provider response exceeded 2 MB.');chunks.push(value);}}finally{await reader.cancel();}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
function safeImage(raw){try{return cleanUrl(raw);}catch{return null;}}
export function saveeCapture(r){const url=cleanUrl(r.url||`https://savee.com/i/${r.short_id}/`);return {originalUrl:url,title:r.name||'Savee reference',origin:'savee',provider:{provider:'savee',id:String(r.id),collection:'saves',updatedAt:r.updated_at||r.created_at||null,url,title:r.name||'Savee reference',description:r.description||'',tags:[],image:safeImage(r.media?.thumbnail||r.media?.original),sourceUrl:r.source_url?cleanUrl(r.source_url):null,savedAt:r.created_at||null}};}
export async function readSavee({token=process.env.SAVEE_TOKEN,fetcher=fetch}={}){if(!token)throw new Error('Set SAVEE_TOKEN on the local service. Generate it in Savee Settings → Developers.');const result=[];let cursor=null;const seen=new Set();for(let page=0;page<200;page++){const url=new URL('https://api.savee.com/v1/saves');url.searchParams.set('limit','100');if(cursor)url.searchParams.set('cursor',cursor);const body=await getJson(url.href,token,fetcher);if(!Array.isArray(body.data))throw new Error('Invalid Savee response.');result.push(...body.data.map(saveeCapture));if(!body.has_more)return result;if(!body.next_cursor||seen.has(body.next_cursor))throw new Error('Savee returned an invalid pagination cursor.');cursor=body.next_cursor;seen.add(cursor);}throw new Error('Savee import exceeds 20,000 saves.');}
export function pinterestCapture(r,board){const url=cleanUrl(`https://www.pinterest.com/pin/${r.id}/`);return {originalUrl:url,title:r.title||'Pinterest reference',origin:'pinterest',provider:{provider:'pinterest',id:String(r.id),collection:String(board),updatedAt:r.created_at||null,url,title:r.title||'Pinterest reference',description:r.description||'',tags:[],image:safeImage(r.media?.images?.['600x']?.url||r.media?.images?.['400x300']?.url),sourceUrl:r.link?cleanUrl(r.link):null,savedAt:r.created_at||null}};}
async function pinterestPages(endpoint,{token=process.env.PINTEREST_TOKEN,fetcher=fetch}={}){if(!token)throw new Error('Set PINTEREST_TOKEN on the local service. Pinterest developer approval and read permissions are required.');const result=[];let bookmark=null;const seen=new Set();for(let page=0;page<200;page++){const url=new URL(`https://api.pinterest.com/v5/${endpoint}`);url.searchParams.set('page_size','100');if(bookmark)url.searchParams.set('bookmark',bookmark);const body=await getJson(url.href,token,fetcher);if(!Array.isArray(body.items))throw new Error('Invalid Pinterest response.');result.push(...body.items);if(!body.bookmark)return result;if(seen.has(body.bookmark))throw new Error('Pinterest returned a repeated page.');bookmark=body.bookmark;seen.add(bookmark);}throw new Error('Pinterest import exceeds 20,000 records.');}
export const readPinterestBoards=async options=>(await pinterestPages('boards',options)).map(b=>({id:b.id,name:b.name}));
export async function readPinterest(board,options){if(!/^\d+$/.test(String(board)))throw new Error('Choose a Pinterest board.');return (await pinterestPages(`boards/${board}/pins`,options)).map(r=>pinterestCapture(r,board));}
